
version: '2'

services:
  gameserver:
    image: gameserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3005:3005
      - 5858:5858
    volumes:
      - .:/usr/src/app
    command: node --debug=5858 gameServer.js
